name: BookCLUB
description: Aplicativo BookCLUB - Grupos e Chats para clubes do livro.
publish_to: 'none' # não será publicado no pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  image_picker: ^1.0.4
  shared_preferences: ^2.2.3
  http: ^1.5.0


  # Ícones e Material 3
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Caso use imagens (ex: ícones do Figma)
  assets:
    - assets/img/

  # Fonte Roboto (como no Figma)
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
